// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwniW3xf_2NyE3UFamM9tHskqBBnfNYD4',
    appId: '1:1062683067615:web:220424f978e75d8d91956a',
    messagingSenderId: '1062683067615',
    projectId: 'quality4360',
    authDomain: 'quality4360.firebaseapp.com',
    storageBucket: 'quality4360.firebasestorage.app',
    measurementId: 'G-8JCJGD44VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsIgDg0PT5vsTaLvnTBvFBdM6G2PRGfqE',
    appId: '1:1062683067615:android:be600b2a2e1f77db91956a',
    messagingSenderId: '1062683067615',
    projectId: 'quality4360',
    storageBucket: 'quality4360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaEIp2DA2mmOwPjnPSOSuVxgsKqcnThoo',
    appId: '1:1062683067615:ios:186cf21601808aaa91956a',
    messagingSenderId: '1062683067615',
    projectId: 'quality4360',
    storageBucket: 'quality4360.firebasestorage.app',
    iosBundleId: 'com.example.surveyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaEIp2DA2mmOwPjnPSOSuVxgsKqcnThoo',
    appId: '1:1062683067615:ios:186cf21601808aaa91956a',
    messagingSenderId: '1062683067615',
    projectId: 'quality4360',
    storageBucket: 'quality4360.firebasestorage.app',
    iosBundleId: 'com.example.surveyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwniW3xf_2NyE3UFamM9tHskqBBnfNYD4',
    appId: '1:1062683067615:web:40b578e9cbbfe68b91956a',
    messagingSenderId: '1062683067615',
    projectId: 'quality4360',
    authDomain: 'quality4360.firebaseapp.com',
    storageBucket: 'quality4360.firebasestorage.app',
    measurementId: 'G-0G86VXTMSC',
  );
}
